### ISSUE TITLE
Query: How can I set the default route after login? 

### ISSUE THREAD

**Issue by simonfanz** [marmelab/ra-auth-msal#13]
When using msalAuthProvider what is the best way to set the default route after login?

**Comment by slax57** [comment]
`ra-auth-msal` has [deep linking](https://github.com/marmelab/ra-auth-msal/blob/main/packages/ra-auth-msal/Readme.md#enabledeeplinkredirect) enabled by default, which means the user will be redirected to the URL they originally requested.

If you disable this feature, the user will be redirected to `window.location.origin`.

If you would like to set a default redirect route, you will need to override the `handleCallback` method in the [authProvider](https://github.com/marmelab/ra-auth-msal/blob/main/packages/ra-auth-msal/src/authProvider.ts#L164).

This could be a feature though, so feel free to open a PR to add this feature (i.e. add a parameter to set a default redirect route).

Since I answered I'll close this issue, but if you'd like to work on the feature let me know, I'll reopen it and mark it as enhancement request so you can reference it in your PR.

Thanks.
